services:

  # 🔵 MySQL
  mysql:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: Preeti@20042004
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  # 🔴 Redis
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

  # 🟢 Spring Boot App
  app:
    build: .
    container_name: spring_app
    ports:
      - "9090:8080"   # IMPORTANT FIX
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Preeti@20042004
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  # 🟡 Adminer (DB UI)
  adminer:
    image: adminer
    container_name: adminer_ui
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  # 🟣 Redis UI
  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis_ui
    ports:
      - "8082:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis
